# Default values for wschallenge.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# -- Port on which the application listens.
appPort: 8080

# -- Overrides names.
nameOverride: ""
fullnameOverride: ""

# -- Environment variables for the application.
env:
  # -- Name of the SQLite database file.
  - name: DB_FILENAME
    value: /data/database.db
  # -- Address on which the application listens.
  - name: ADDRESS
    value: "0.0.0.0"

# -- Number of replicas for the application.
replicaCount: 1

image:
  # -- Repository of the Docker image.
  repository: jamorosoa/tengen-tetris-ws-challenge-gh
  # -- Pull policy for the Docker image.
  pullPolicy: Always
  # -- Tag of the Docker image.
  tag: "1.0.0"

service:
  # -- Type of Kubernetes service.
  type: NodePort

ingress:
  # -- Specifies whether ingress should be enabled.
  enabled: true
  # -- Ingress class name.
  className: alb
  # -- Annotations for the ingress, assuming we are using AWS Load Balancer controller for ingress.
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
  # -- Hosts and paths for the ingress.
  hosts:
    - host: wschallenge1.joseamoroso.com
      paths:
        - path: /
          pathType: Prefix

# -- Resource requests and limits for the pods.
resources:
  limits:
    cpu: 1000m
    memory: 256Mi
  requests:
    cpu: 1000m
    memory: 128Mi

autoscaling:
  # -- Specifies whether autoscaling should be enabled.
  enabled: true
  # -- Minimum number of replicas.
  minReplicas: 2
  # -- Maximum number of replicas.
  maxReplicas: 10
  # -- Target CPU utilization percentage.
  targetCPUUtilizationPercentage: 70
  # -- Target memory utilization percentage.
  targetMemoryUtilizationPercentage: 70

# -- Node selector for pods.
nodeSelector: {}

# -- Tolerations for pods.
tolerations: []

# -- Affinity for pods.
affinity: {}

# -- Volume settings.
volume:
  # -- Specifies whether volume should be enabled.
  enabled: true
  # -- Name of the volume.
  name: data
  # -- Path where the volume is mounted inside the container.
  path: /data
  # -- Server information if using an external volume. This id correspond to EFS volume generated in AWS. E.g. fs-xxxxxxxxxxxxxx
  server:
