apiVersion: v1
kind: Service
metadata:
  name: {{ include "wschallenge.fullname" . }}
  labels:
    {{- include "wschallenge.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.appPort }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "wschallenge.selectorLabels" . | nindent 4 }}
